// sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  guideSidebar: [
    // Keep these explicitly at the top
    'intro',
//    'principles',
//    'about',

    // Everything else is generated automatically from /docs
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};
